### ISSUE TITLE
Problem building NetBricks

### ISSUE THREAD

**Issue by ztz1989** [NetSys/NetBricks#103]
Hi, all. I am trying to build NetBrick from scratch. I followed the instructions and encountered a problem after running build.sh, the output is as follows:

sudo ./build.sh 
DPDK found not building
Building rust
Done with deps
make: Entering directory '/home/tzhang/NetBricks/native'
make[1]: Nothing to be done for 'all'.
make: Leaving directory '/home/tzhang/NetBricks/native'
make: Entering directory '/home/tzhang/NetBricks/native'
cp libzcsi.so /home/tzhang/NetBricks/target/native
make: Leaving directory '/home/tzhang/NetBricks/native'
SCTP library found
~/NetBricks/framework ~/NetBricks
./build.sh: line 304: build: command not found

Could you help me find out the problem? Thanks a lot!!

  Best regards,
  Tianzhu

**Comment by a5135324** [comment]
I get the same problem.
Can someone help me to deal with it?
