### ISSUE TITLE
Support for OSX

### ISSUE THREAD

**Issue by djKooks** [NetSys/NetBricks#13]
Hello~
Do you have plan to support OSX platform? It causes error on build.sh.
(I changed `nproc` to `sysctl -n hw.physicalcpu`, but it still not work)

**Comment by apanda** [comment]
No, unfortunately DPDK is not supported on OS X.

Sorry.

**Comment by apanda** [comment]
If you just wanted to build, the container build option (#14) should allow for that.

**Comment by djKooks** [comment]
Okay. Thanks~
