### ISSUE TITLE
a bug in ip.rs ?

### ISSUE THREAD

**Issue by jackyangNJ** [NetSys/NetBricks#49]
Hello,
 I was testing the module aclfw, however, I found it cannot work correctly when I wanted to filter a specified source port.
I looked up into the code of ip.rs used by aclfw.
![code snap from ip rs](https://cloud.githubusercontent.com/assets/4023707/26389008/443dccbc-408a-11e7-8c57-47aacdd437d2.png)
`let port_as_u8 = self_as_u8.offset(self.length() as isize);`, the offset value may be wrong. `self.length()` is the whole length of ip packet, not the ip header length.
So `let dst_port = BigEndian::read_u16(&port_slice[..16]);` gets the wrong value.
Also, `port_slice[..16]` may not be right.

Thanks!

**Comment by sirspinach** [comment]
Thanks for pointing this out, Jack!
