### ISSUE TITLE
Unresolved Import, No Allocate in Heap - Rust 1.21.0

### ISSUE THREAD

**Issue by shelbyt** [NetSys/NetBricks#78]
Getting an error using the rust nightly build instructions.
Unresolved import 'alloc::heap::allocate'
no 'allocate' in 'heap'

System:
Ubuntu 14.04.
Rust 1.21.0

<img width="940" alt="rust-net-err" src="https://user-images.githubusercontent.com/1332316/28953035-395f5864-788a-11e7-9cb3-f7a23ac2ffc9.PNG">

Any ideas would be appreciated, thanks!

**Comment by apanda** [comment]
Fixed by #79
