### ISSUE TITLE
question to packet.rs

### ISSUE THREAD

**Issue by rstade** [NetSys/NetBricks#84]
Hi,
first of all congratulations for this excellent work! I really like your approach of applying functions to packets vs. the traditional transporting packets to functions approach. I think this is absolutely the right way to go.

Just a question to your code in "packet.rs"  line 312. In my view this statement "let header=self.payload();" hides the "header"-argument of the push_header function. I commented that line out and the code works fine for me. Or what is the intention of this line of code?

**Comment by apanda** [comment]
Good point, that is a bug. Thanks for reporting it, sorry about any trouble it might have caused.

**Comment by apanda** [comment]
Fixed by f8c0f118 -- it is slighly more involved than just removing the line.
