### ISSUE TITLE
missing field `dpdk_args` in initializer of `config::NetbricksConfiguration`

### ISSUE THREAD

**Issue by ankit-iitb** [NetSys/NetBricks#87]
I am following the commands given in the readme file and I am getting the following error when I run 

./build.sh build

__### error[E0063]: missing field `dpdk_args` in initializer of `config::NetbricksConfiguration`_
   _--> src/config/config_reader.rs:290:8
    |
290 |     Ok(NetbricksConfiguration {
    |        ^^^^^^^^^^^^^^^^^^^^^^ missing `dpdk_args`

error: aborting due to previous error

error: Could not compile `e2d2`.

To learn more, run the command again with _--verbose.___

Am I missing something? Please help me in this regards.

Thanks.

**Comment by dimbleby** [comment]
fixed in #85

**Comment by Anmol-007** [comment]
Thank you for your quick response.

**Comment by ankit-iitb** [comment]
Thank @dimbleby  for the quick response.
