### ISSUE TITLE
Error pops up while compiling etcdv3-rs

### ISSUE THREAD

**Issue by magicwwh** [NetSys/NetBricks#94]
Hi All,

I try to build NetBricks on my machine, but the compiling error of etcdv3-rs keeps occurring.
Could you please provide me any hint to solve the problem. Thanks in advance.
Below is the error info:
    
SCTP library found
~/dev/NetBricks/framework ~/dev/NetBricks
   Compiling etcdv3-rs v0.1.0 (https://github.com/apanda/etcdv3-rs#b99b7919)
error[E0599]: no method named `and_then` found for type `hyper::client::FutureResponse` in the current scope
  --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:34:51
   |
34 |         Box::new(self.client.request(put_request).and_then(
   |                                                   ^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           candidate #1: `use futures::future::Future;`

error[E0277]: the trait bound `futures::Future<Error=hyper::Error, Item=bool>: std::marker::Sized` is not satisfied
  --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:34:9
   |
34 |         Box::new(self.client.request(put_request).and_then(
   |         ^^^^^^^^ `futures::Future<Error=hyper::Error, Item=bool>` does not have a constant size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `futures::Future<Error=hyper::Error, Item=bool>`
   = note: required by `<std::boxed::Box<T>>::new`

error[E0599]: no method named `and_then` found for type `hyper::client::FutureResponse` in the current scope
  --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:55:18
   |
55 |                 .and_then(|res| res.body().concat2())
   |                  ^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           candidate #1: `use futures::future::Future;`

error[E0277]: the trait bound `[u8]: std::marker::Sized` is not satisfied
  --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:56:28
   |
56 |                 .and_then(|body| {
   |                            ^^^^ `[u8]` does not have a constant size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `[u8]`
   = note: all local variables must have a statically known size

error[E0277]: the trait bound `futures::Future<Error=hyper::Error, Item=std::option::Option<std::string::String>>: std::marker::Sized` is not satisfied
  --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:52:9
   |
52 |         Box::new(
   |         ^^^^^^^^ `futures::Future<Error=hyper::Error, Item=std::option::Option<std::string::String>>` does not have a constant size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `futures::Future<Error=hyper::Error, Item=std::option::Option<std::string::String>>`
   = note: required by `<std::boxed::Box<T>>::new`

error[E0599]: no method named `and_then` found for type `hyper::client::FutureResponse` in the current scope
  --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:82:18
   |
82 |                 .and_then(|res| res.body().concat2())
   |                  ^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           candidate #1: `use futures::future::Future;`

error[E0277]: the trait bound `[u8]: std::marker::Sized` is not satisfied
  --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:83:28
   |
83 |                 .and_then(|body| {
   |                            ^^^^ `[u8]` does not have a constant size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `[u8]`
   = note: all local variables must have a statically known size

error[E0277]: the trait bound `futures::Future<Error=hyper::Error, Item=std::vec::Vec<(std::string::String, std::string::String)>>: std::marker::Sized` is not satisfied
  --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:79:9
   |
79 |         Box::new(
   |         ^^^^^^^^ `futures::Future<Error=hyper::Error, Item=std::vec::Vec<(std::string::String, std::string::String)>>` does not have a constant size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `futures::Future<Error=hyper::Error, Item=std::vec::Vec<(std::string::String, std::string::String)>>`
   = note: required by `<std::boxed::Box<T>>::new`

error[E0599]: no method named `and_then` found for type `hyper::client::FutureResponse` in the current scope
   --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:118:18
    |
118 |                 .and_then(|res| res.body().concat2())
    |                  ^^^^^^^^
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
            candidate #1: `use futures::future::Future;`

error[E0277]: the trait bound `[u8]: std::marker::Sized` is not satisfied
   --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:119:28
    |
119 |                 .and_then(|body| {
    |                            ^^^^ `[u8]` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `[u8]`
    = note: all local variables must have a statically known size

error[E0277]: the trait bound `futures::Future<Error=hyper::Error, Item=etcd_proto::RangeResponse>: std::marker::Sized` is not satisfied
   --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:115:9
    |
115 |         Box::new(
    |         ^^^^^^^^ `futures::Future<Error=hyper::Error, Item=etcd_proto::RangeResponse>` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `futures::Future<Error=hyper::Error, Item=etcd_proto::RangeResponse>`
    = note: required by `<std::boxed::Box<T>>::new`

error[E0599]: no method named `and_then` found for type `hyper::client::FutureResponse` in the current scope
   --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:145:53
    |
145 |         Box::new(self.client.request(watch_request).and_then(|res| {
    |                                                     ^^^^^^^^
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
            candidate #1: `use futures::future::Future;`

error[E0277]: the trait bound `[u8]: std::marker::Sized` is not satisfied
   --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:146:41
    |
146 |             Ok(Box::new(res.body().map(|chunk| {
    |                                         ^^^^^ `[u8]` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `[u8]`
    = note: all local variables must have a statically known size

error[E0277]: the trait bound `futures::Future<Error=hyper::Error, Item=std::boxed::Box<futures::Stream<Item=etcd_proto::WatchResponse, Error=hyper::Error>>>: std::marker::Sized` is not satisfied
   --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:145:9
    |
145 |         Box::new(self.client.request(watch_request).and_then(|res| {
    |         ^^^^^^^^ `futures::Future<Error=hyper::Error, Item=std::boxed::Box<futures::Stream<Item=etcd_proto::WatchResponse, Error=hyper::Error>>>` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `futures::Future<Error=hyper::Error, Item=std::boxed::Box<futures::Stream<Item=etcd_proto::WatchResponse, Error=hyper::Error>>>`
    = note: required by `<std::boxed::Box<T>>::new`

error[E0599]: no method named `and_then` found for type `hyper::client::FutureResponse` in the current scope
   --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:174:53
    |
174 |         Box::new(self.client.request(watch_request).and_then(|res| {
    |                                                     ^^^^^^^^
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
            candidate #1: `use futures::future::Future;`

error[E0277]: the trait bound `[u8]: std::marker::Sized` is not satisfied
   --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:175:41
    |
175 |             Ok(Box::new(res.body().map(|chunk| {
    |                                         ^^^^^ `[u8]` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `[u8]`
    = note: all local variables must have a statically known size

error[E0277]: the trait bound `futures::Future<Error=hyper::Error, Item=std::boxed::Box<futures::Stream<Item=etcd_proto::WatchResponse, Error=hyper::Error>>>: std::marker::Sized` is not satisfied
   --> /home/wenhao/.cargo/git/checkouts/etcdv3-rs-36c166c6e775c7cf/b99b791/src/etcd_actions.rs:174:9
    |
174 |         Box::new(self.client.request(watch_request).and_then(|res| {
    |         ^^^^^^^^ `futures::Future<Error=hyper::Error, Item=std::boxed::Box<futures::Stream<Item=etcd_proto::WatchResponse, Error=hyper::Error>>>` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `futures::Future<Error=hyper::Error, Item=std::boxed::Box<futures::Stream<Item=etcd_proto::WatchResponse, Error=hyper::Error>>>`
    = note: required by `<std::boxed::Box<T>>::new`

error: aborting due to 17 previous errors

Some errors occurred: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: Could not compile `etcdv3-rs`.

**Comment by apanda** [comment]
Fixed by c03bf0f
